### ISSUE TITLE
CKAN doesn't like mods that have many things fill one requirement.

### ISSUE THREAD

**Issue by FireFaced** [KSP-CKAN/CKAN#1274]
So, I was installing Kofeyh's CKAN file ( http://pastebin.com/raw.php?i=JTsdniZf ) to get all his mods installed, but this error was thrown:

```
 *************\* Exception Text **************
 CKAN.TooManyModsProvideKraken: Too many mods provide RealFuels-Engine-Configs:
 RFStockalike v2.1.7
 - RealismOverhaul v10.1.0
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions >options)
   at CKAN.RelationshipResolver.ResolveStanza(IEnumerable`1 stanza, SelectionReason reason, RelationshipResolverOptions options, Boolean soft_resolve)
   at CKAN.RelationshipResolver.Resolve(CkanModule module, RelationshipResolverOptions >options)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.ModuleInstaller.InstallList(List`1 modules, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.WasSuccessful(Action action)
   at CKAN.Main.InstallList(HashSet`1 toInstall, RelationshipResolverOptions options, IDownloader downloader)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by FireFaced** [comment]
Markdown is being weird.

**Comment by FireFaced** [comment]
Anyone?

**Comment by Wetmelon** [comment]
I also get this exception with my own CKAN file for Real Solar System, except it's for the "RSSTextures".

Real Solar System has a "RSSTextures (virtual)" depends, with 3 "provided by" options.

Real Fuels has "RealFuels-Engine-Configs (virtual)" with either RealFuels: Stockalike RF Configs, or RealismOverhaul providing options.

Evidently, this error occurs when multiple options satisfy the virtual dependency.

**Comment by Wetmelon** [comment]
Okay, I was able to get it to work by eliminating the Kraken and using soft_resolve, effectively making it iterate through the options until it gets to the correct, non-conflicting one.

**Comment by FireFaced** [comment]
Do note that this is the GUI

**Comment by pjf** [comment]
To diagnose, we're going to need at least:

* CKAN version
* Steps to reproduce (GUI? Command-line? `install -c`? `Install-from CKAN...`? Added to upstream repo?)

I *do* know the GUI handles `.ckan` installs from the way in which the command-line handles things, so you could potentially get away with `ckan.exe install -c YourFile.ckan` and see if that makes a difference.

**Comment by Wetmelon** [comment]
Open CKAN Gui.  File -> Install from .CKAN -> Browse & select Test.ckan; link below:
https://www.dropbox.com/s/kg95839nyng6qj6/Test.ckan?dl=0

CKAN version 1.10.0-0-gb447380 (beta) - KSP 1.0.4
Also reproducible on self-build from current Master branch.

**Comment by FireFaced** [comment]
@Wetmelon did this correctly. Pjf, just to see my steps, look below.
CKAN 1.10.0-0-gb447380
Open GUI. File > Install from .CKAN > Use a CKAN file that includes a mod that can have many things fill one dependency.

Find that it is complaining about a TooManyProvidesKraken, even though an option is specified in the CKAN file.

**Comment by Wetmelon** [comment]
Still occurs in 1.10.3

**Comment by Postremus** [comment]
@FireFaced is this issue fixed with CKAN 1.14.0?

**Comment by FireFaced** [comment]
I haven't tried

**Comment by tjanke42** [comment]
I can confirm this is still an issue as of Nov 21, 2016 with CKAN 1.20.1.

I can't update scatterer, because both scatterer and SVE provide 'scatterer-sunflare'.  CKAN presents me with a choice as to which mod I'd like to provide 'scatterer-sunflare', but no matter which I choose, it fails with TooManyModsProvideKraken.

:(

**Comment by politas** [comment]
There have been a lot of changes to the way dependencies are handled between Scatterer and SVE. Uninstall all related mods and pick SVE. Everything else should work fine, then.

**Comment by tjanke42** [comment]
Ok.  Good advice, thanks.

**Comment by mwerle** [comment]
Tried to install EVE (CKAN 1.22.5) and I got this error.  I managed to install EVE on another computer fine (but may have been using CKAN1.22.3).  I picked a different (lower-res) configuration for the laptop. Not sure how to reproduce since the mods are not marked as installed, but it no longer goes through the entire set of dependency questions as the first time around.

Any way to check/reset the CKAN state?

**Comment by devnoo** [comment]
Got same problem install Real Solar System
Seems to be a bug in 1.22.5, just reverted to 1.22.3 and problem was gone.

**Comment by politas** [comment]
The workaround for this is to select the config/texture providing mod first.But, we definitely need to track this down and fix it. I suspect #2073 is the culprit.

**Comment by politas** [comment]
Ok, #2073 is fine.

**Comment by politas** [comment]
Ok, turns out it was #1929 that was causing the problem.

**Comment by HebaruSan** [comment]
I downloaded the file from the original pastebin and removed the version numbers, and it installed OK onto a KSP 1.2.2 instance:

```
$ mono ckan.exe install -c installed-default-versionless.ckan  --ksp 1.2.2
1) Scatterer-config (scatterer - default config)
2) SSRSS-Cont (SSRSS Continued)
3) SVE-Scatterer-Config (Stock Visual Enhancements: Scatterer Configs)
Enter a number between 1 and 3 (To cancel press "c" or "n".): 
1
About to install...

 * scatterer - default config 2:v0.0320(cached)
 * Kerbal Engineer Redux 1.1.2.8(cached)
 * Kerbal Joint Reinforcement v3.3.2(cached)
 * MechJeb 2 2.6.0.0(cached)
 * Real Plume 2:v11.0.0(cached)
 * Module Manager 2.7.6(cached)
 * SmokeScreen - Extended FX Plugin 2.7.4.0(cached)
 * Real Plume - Stock Configs v0.11.4(cached)
 * Engine Lighting 1.5(cached)
 * (Semi)Saturatable Reaction Wheels 1.12(cached)
 * Astroniki Sunflare for Scatterer 1.2(cached)
 * scatterer 2:v0.0320(cached)

Continue? [Y/n] 


Installing mod "Scatterer-config 2:v0.0320"
Installing mod "KerbalEngineerRedux 1.1.2.8"
Installing mod "KerbalJointReinforcement v3.3.2"
Installing mod "MechJeb2 2.6.0.0"
Installing mod "RealPlume 2:v11.0.0"
Installing mod "ModuleManager 2.7.6"
Installing mod "SmokeScreen 2.7.4.0"
Installing mod "RealPlume-StockConfigs v0.11.4"
Installing mod "EngineLighting 1.5"
Installing mod "SemiSaturatableRW 1.12"
Installing mod "AstronikiSunflareforScatterer 1.2"
Installing mod "Scatterer 2:v0.0320"
Updating registry
Commiting filesystem changes
Rescanning GameData
Done!
```

Closing as it seems to be fixed.
