### ISSUE TITLE
KSP max version is not correctly detected

### ISSUE THREAD

**Issue by ihsoft** [KSP-CKAN/CKAN#2551]
Background
----------

**CKAN Version:** v1.24.0

**KSP Version:** 1.5.1

**Operating System:** Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Installed some mods, but not the one in question.

Problem
-------

**What steps did you take in CKAN?**

Loaded and refreshed the database.

**What did you expect to happen?**

Mod `KSPDev LogConsole` is expected to reflect the latest version (`v0.21` as of today) with KSP max version `1.5.99`.

**What happened instead?**

For mod `KSPDev LogConsole` CKAN says the maximum version is `1.4.99`. I've checked `CKAN/downloads` folder and found the archive for `v0.21` - it properly specifies the maximum version:

```
    "KSP_VERSION": {
        "MAJOR": 1, 
        "MINOR": 5, 
        "PATCH": 0
    }, 
    "KSP_VERSION_MAX": {
        "MAJOR": 1, 
        "MINOR": 5, 
        "PATCH": 99
    }, 
    "KSP_VERSION_MIN": {
        "MAJOR": 1, 
        "MINOR": 4, 
        "PATCH": 0
    }, 
```

The [NetKAN metafile](https://github.com/KSP-CKAN/CKAN-meta/blob/master/KSPDev-LogConsole/KSPDev-LogConsole-0.21.ckan) seems to be valid as well:

```
    "version": "0.21",
    "ksp_version_min": "1.4.0",
    "ksp_version_max": "1.5.99",
```

When I had `v0.19` in my system, CKAN was showing that the newest version is `v0.21`, but it was not offering to upgrade it. I guess, it's because it was assuming the KPS version is incompatible.

One more detail which may help. Some time ago I've changed the mod's repository. The appropriate NetKAN files were updated.

**Screenshots:**

![ckan issue](https://user-images.githubusercontent.com/7295777/47405805-2e390880-d708-11e8-8463-dd5961b4abbf.png)

**Comment by ihsoft** [comment]
Done. Let's see if it helps. Thanks!

**Comment by ihsoft** [comment]
It helped. Thanks!

**Comment by 7ranceaddic7** [comment]
About that epoch thingy ...

1. I'm still seeing it.
2. I have hide epoch ticked.

![ckan-epoch](https://user-images.githubusercontent.com/4062616/47459828-f7a7d000-d791-11e8-9ad8-8cbf9c1ec69d.png)

**Comment by HebaruSan** [comment]
That setting is only for the mod list, the big grid on the left.
