### ISSUE TITLE
[Bug] Can't build on Manjaro

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2898]
Background
----------
* Operating System: Manjaro Linux
* CKAN Version: Current Master branch
* Mono Version: 6.0.0.334-1
* msbuild-stable version: 16.0_xamarinxplat.2018.09.26.17.53_0xamarin3_ubuntu1404b1-1

Problem
-------
**Describe the bug**
Build process uses msbuild version 15.0 from /usr/lib/mono/msbuild/15.0/bin rather than /usr/bin/msbuild

**Steps to reproduce**
```./build``` with environment as above

**Expected behavior**
App builds

**Build output**
https://pastebin.com/9mnfsiaq

**Comment by HebaruSan** [comment]
> /usr/lib/mono/msbuild/15.0/bin/Microsoft.CSharp.CurrentVersion.targets(331,5): error MSB4019: The imported project "/usr/lib/mono/msbuild/15.0/bin/Roslyn/Microsoft.CSharp.Core.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. 

I think that means you're missing some files that are supposed to be installed. It works for me:

```
$ mono --version
Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:21:28 UTC 2019)
```

**Comment by politas** [comment]
Trouble is that it's trying to use the msbuild from the base "mono" installation instead of the msbuild installed by msbuild-stable.

**Comment by politas** [comment]
If I symlink /usr/lib/mono/msbuild/current/bin/Roslyn to /usr/lib/mono/msbuild/15.0/bin/Roslyn, I can compile. But we shouldn't be using the outdated mono msbuild when we've got a more up-to-date msbuild available

```
$ msbuild /version
Microsoft (R) Build Engine version 16.0.0.0 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by techman83** [comment]
I'm using the mono project repo directly on linux mint.
```bash
➜  CKAN git:(master) mono --version
Mono JIT compiler version 6.4.0.198 (tarball Tue Sep 24 01:21:28 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
➜  CKAN git:(master) apt-cache policy mono-complete
mono-complete:
  Installed: 6.4.0.198-0xamarin3+ubuntu1804b1
  Candidate: 6.4.0.198-0xamarin3+ubuntu1804b1
  Version table:
 *** 6.4.0.198-0xamarin3+ubuntu1804b1 500
        500 https://download.mono-project.com/repo/ubuntu stable-bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     4.6.2.7+dfsg-1ubuntu1 500
        500 http://mirror.waia.asn.au/ubuntu bionic/universe amd64 Packages
```
On my system, 15.0 is linked to Current. Is it a packaging issue or Cake doing something weird?
```bash
➜  CKAN git:(master) ls -lah /usr/lib/mono/msbuild/15.0
lrwxrwxrwx 1 root root 7 Jul 18 22:07 /usr/lib/mono/msbuild/15.0 -> Current
➜  CKAN git:(master) msbuild /version
Microsoft (R) Build Engine version 16.3.0-ci for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

16.300.19.41901% 
➜  CKAN git:(master) apt-cache policy msbuild              
msbuild:
  Installed: 1:16.3+xamarinxplat.2019.08.08.00.55-0xamarin2+ubuntu1804b1
  Candidate: 1:16.3+xamarinxplat.2019.08.08.00.55-0xamarin2+ubuntu1804b1
  Version table:
 *** 1:16.3+xamarinxplat.2019.08.08.00.55-0xamarin2+ubuntu1804b1 500
        500 https://download.mono-project.com/repo/ubuntu stable-bionic/main amd64 Packages
        500 https://download.mono-project.com/repo/ubuntu stable-bionic/main i386 Packages
        100 /var/lib/dpkg/status
```

**Comment by politas** [comment]
Might be Cake that is going looking for msbuild and choosing to use the older version buried in mono rather than the newer version that is in the command path.

**Comment by politas** [comment]
I don't know why mono - project embed msbuild in the mono package as well as providing it as a separate tool.

**Comment by HebaruSan** [comment]
Any relation to #2842 ?

**Comment by HebaruSan** [comment]
Reportedly fixed in #2921.

**Comment by Calvinxc1** [comment]
I am still getting this error when trying to install via pacman, is there something I should be doing differently?

**Comment by DasSkelett** [comment]
> I am still getting this error when trying to install via pacman, is there something I should be doing differently?

The fix is not released yet, however the next CKAN release should come soon.

**Comment by Calvinxc1** [comment]
Schaweet! Thank you!

**Comment by politas** [comment]
@Calvinxc1, I've updated the AUR with the new release. Can you test install via pacman, now?

**Comment by Calvinxc1** [comment]
Woot! All looks good! Thanks much!
