### ISSUE TITLE
[Bug]:  Unsatisfied dependency when trying to install RP-1 Express Install

### ISSUE THREAD

**Issue by sckxmfi** [KSP-CKAN/CKAN#4414]
### Is there an existing issue for this?

- [x] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

MacOS

### CKAN Version

Quasar

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

I have made no changes to my game data folder manually.

### Describe the bug

When trying to install KSP RP-1 Express Install on Mac, I get an error saying  

```
Unsatisfied dependency RealFuels-Engine-Configs (KSP All versions) needed for: RealFuels 1:v15.12.0.0   
```

When I install RealFuels and StockConfigs, I get another dependency error 

```
 Unsatisfied dependency RealismOverhaul (KSP 0.25–1.12.99) needed for:   
 ROEngines v2.13.3.0 (needed for RP-1-ExpressInstall v2.0); ROHeatshields 
    v1.3.0.0 (needed for RP-1-ExpressInstall v2.0); ROCapsules v2.7.0.0   
                   (needed for RP-1-ExpressInstall v2.0)        
```

### Steps to reproduce

Go to CKAN on Mac
Shift-Plus RP-1-ExpressInstall
Choose dependencies and optional mods (I didn't change what it told me to install, chose high graphics and RP-1 to enable career mode)
F9 until you get to the point where you can install
Prompt of Unsatisfied Dependencies pops up.

**Comment by HebaruSan** [comment]
Hi @sckxmfi, there's a bug in v1.36.0 affecting how failed downloads are handled (fixed in #4367), and what you described sounds like an instance of that problem. If you try the dev build, you should be able to see the actual download error:

- <https://ksp-ckan.s3-us-west-2.amazonaws.com/CKAN.dmg>

**Comment by sckxmfi** [comment]
Hey @HebaruSan When I downloaded the dev build, The same problems still occurred in the dev build, meaning I think there is something wrong with the way CKAN installs RP-1's Express Install or the way it handles some dependencies.

**Comment by HebaruSan** [comment]
Hi @sckxmfi, can you please share a screenshot of the problem you have with the dev build, so we can confirm that it's actually the same? Thanks!

**Comment by sckxmfi** [comment]
When I go to install RP-1ExpressInstall on a fresh ksp 1.12.5

<img width="656" height="430" alt="Image" src="https://github.com/user-attachments/assets/489aaa4a-99b1-4d3d-a4ca-7abc04ac7ca4" />

When I Install RealFuels and RealFuels-Stock (config for stock fuels and other mods) then try to instal RP-1-ExpressInstall

<img width="619" height="403" alt="Image" src="https://github.com/user-attachments/assets/e8c3b7b8-e130-4b0a-8126-88070cb9fbed" />

**Comment by HebaruSan** [comment]
Thanks! There is indeed more going on here than I expected was the case. Luckily, I'm able to reproduce the issue locally, which will make investigating it much easier...

**Comment by HebaruSan** [comment]
> When I Install RealFuels and RealFuels-Stock (config for stock fuels and other mods) then try to instal RP-1-ExpressInstall

It might be worth trying RealFuels with RealismOverhaul instead of RealFuels-Stock, since you're going for RP-1 and RealismOverhaul is one of the other mods providing RealFuels-Engine-Configs according to the CKAN GUI:

<img width="337" height="239" alt="Image" src="https://github.com/user-attachments/assets/ab72435d-4c9e-49e5-b1a2-07c0169bcb22" />

**Comment by sckxmfi** [comment]
When installing RP1ExpressInstall it threw me an error for needing a config for RF, but didn't give me an option to chose what config I want. CKAN tells me RF requires me to download a specific config file for RF (RealFuels-Engine-Config) when it gives me the error while trying to install RP-1-ExpressInstall. CKAN should have given me the option to install a config from RF-EngineConfig or RO, but it did not give me an option to chose between stock config or RO and the config that comes with RO since RO itself includes a config for RF. RF stock config and RO both did not even show up when CKAN prompted me the dependencies RP1ExpressInstall needed. I there might be a problem with either how CKAN handles dependencies or more likely a problem with RP-1-ExpressInstall, So for now the solution will have to be to download RO before your install RP-1-ExpressInstall. Sorry if this was a pointless bug report

**Comment by HebaruSan** [comment]
Hi @sckxmfi, not pointless at all. Thank you for reporting this, I am investigating it and will continue until I've figured it out.

**Comment by HebaruSan** [comment]
@sckxmfi, in the course of investigating this, I have discovered that I can bypass the problem by de-selecting the recommendation for `ROEngines` (which also depends on `RealFuels`). So another workaround option is to do that and then install `ROEngines` later.
